### ISSUE TITLE
Create Content of Parents Letter to MC

### ISSUE THREAD

**Issue by bridgettorres** [bridgettorres/Nightshade-Academy#41]

**Comment by bridgettorres** [comment]
Some where around the lines mention the fact that the you are a raffle student that was lucky enough to have gained admission to Nightshade Academy.

**Comment by JCCline22** [comment]
Hi Sweetie, 

I know staying away from home can be scary, but you can do this! Just because you got in through the raffle does not make you any less worthy than the selected kids. You have so much unrealized potential, you're smart just like your father, hopefully that's the only way you're like him. I know I won't be hearing from you for a while because of the school's policies, remember, dear, boarding school is for those who can't quite manage at home. Just kidding! Have a fantastic time my little genius. Don't forget to write back when you can.

 Good Luck! I am so excited for you.
- Love, Mom
